name: Feature Request
description: Suggest a new feature or enhancement for Chronapse
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: |
        I'm frustrated when...
        It would be helpful if...
        I need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: Detailed description of your proposed feature...
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe real-world scenarios where this feature would be useful
      placeholder: |
        1. When recording a sunset, I would use this feature to...
        2. For long-term project monitoring, this would help by...
        3. When creating timelapses of...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        - Alternative 1: ...
        - Alternative 2: ...
        - Current workaround: ...
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - UI/UX Enhancement
        - New Recording Feature
        - Export/Output Option
        - Performance Improvement
        - Configuration Option
        - Integration with External Tool
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my use of Chronapse
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have technical ideas about how to implement this, please share
      placeholder: |
        Technical approach:
        - Could use library X for...
        - Might need to modify component Y...
        - Integration with Z would require...
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, diagrams, or examples from other tools
      placeholder: Drag and drop images here, or provide links to similar features...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request
      placeholder: |
        - Related to issue #...
        - Similar to feature in application X...
        - Would work well with...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you interested in contributing this feature?
      options:
        - label: I would be willing to submit a PR to implement this feature
          required: false
        - label: I would be willing to help test this feature
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to ensure this hasn't been requested
          required: true
        - label: I have checked the project roadmap and TODO list
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true
