name: Question
description: Ask a question about using or developing Chronapse
title: "[Question]: "
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please fill out the form below.

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation and Setup
        - Usage and Configuration
        - Troubleshooting
        - Development and Contributing
        - Feature Clarification
        - Performance and Optimization
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please describe your question in detail
      placeholder: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context that might help us answer your question
      placeholder: |
        - What are you trying to accomplish?
        - What have you already tried?
        - What documentation have you consulted?
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: If your question is environment-specific, please provide details
      placeholder: |
        - OS:
        - Chronapse version:
        - Go version:
        - Python version:
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other information that might be helpful
      placeholder: Links, screenshots, code snippets, etc.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have read the README.md and USAGE.md documentation
          required: true
        - label: I have searched existing issues for similar questions
          required: true
        - label: This is not a bug report (use the Bug Report template instead)
          required: true
